[package]
name = "athena-test"
version = "0.1.0"
authors = ["Derek Morr <derekmorr@psu.edu>"]
edition = "2018"

[dependencies]
rusoto_core = "0.36.0"
rusoto_athena = "0.36.0"
env_logger = "0.6.0"
uuid = { version = "0.7", features = ["serde", "v4"] }